-- --------------------------------------------------------
-- Host:                         localhost
-- Versión del servidor:         5.7.24 - MySQL Community Server (GPL)
-- SO del servidor:              Win32
-- HeidiSQL Versión:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;



-- Volcando estructura para tabla municipalidad.institucion_educativa
CREATE TABLE IF NOT EXISTS `institucion_educativa` (
  `id_institucion` int(11) NOT NULL AUTO_INCREMENT,
  `inst_nombre` varchar(500) COLLATE utf8_spanish_ci NOT NULL,
  `inst_ubicacion` varchar(500) COLLATE utf8_spanish_ci,
  `inst_email` varchar(500) COLLATE utf8_spanish_ci,
  `inst_contacto` varchar(500) COLLATE utf8_spanish_ci,
  `inst_sitio_web` varchar(1500) COLLATE utf8_spanish_ci DEFAULT NULL,
  `instagram` varchar(1500) COLLATE utf8_spanish_ci DEFAULT NULL,
  `facebook` varchar(1500) COLLATE utf8_spanish_ci DEFAULT NULL,
  `horarios_de_atencion` varchar(1500) COLLATE utf8_spanish_ci DEFAULT NULL,
  PRIMARY KEY (`id_institucion`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Se registran todas las instituciones educativas de nivel Terciario y Universitario que hay en Tres Arroyos';

-- Volcando datos para la tabla municipalidad.institucion_educativa: ~11 rows (aproximadamente)
/*!40000 ALTER TABLE `institucion_educativa` DISABLE KEYS */;
INSERT INTO `institucion_educativa` (`id_institucion`, `inst_nombre`, `inst_ubicacion`, `inst_email`, `inst_contacto`, `inst_sitio_web`, `instagram`, `facebook`, `horarios_de_atencion`) VALUES
	(1, 'CRESTA', 'MAIPU 270', 'cresta@cresta.edu.ar', '02983-430131', 'http://www.cresta.edu.ar/', 'https://www.instagram.com/crestaoficial/', 'https://www.facebook.com/crestaoficial', NULL),
	(2, 'ISFD N° 167\r\n', 'Dr. Dameno 50', 'isfd167tresarroyos@abc.gob.ar', '02983-422179', 'https://isfd167-bue.infd.edu.ar/', 'https://www.instagram.com/isfd167_oficial/', 'https://www.facebook.com/people/ISFD-N%25C2%25BA-167-de-Tres-Arroyos-Oficial/100063506532173/?ref=bookmarks', NULL),
	(3, 'ISFDyT 33\r\n', 'Sarmiento 50', 'isfdyt33@gmail.com', '02983-423186', 'https://isfdyt33-bue.infd.edu.ar/sitio/', 'https://www.instagram.com/instituto_33', '', NULL),
	(4, 'CGT', 'Betolaza 317', 'cfp401@gmail.com', '02983-430157', 'https://www.cfp401tsas.edu.ar', 'https://www.instagram.com/cfl401_tresarroyos/?hl=es', 'https://www.facebook.com/cfp.tresarroyos/?locale=es_LA', NULL),
	(5, 'Universidad Siglo 21', 'Maipu 10 Piso 1', 'Ues21tresarroyos@bvconline.com.ar', '02983-431169', 'https://21.edu.ar/', 'https://www.instagram.com/siglo21.tresarroyos/', NULL, 'Lunes a Viernes de 9 a 13 Hs y de 16 a 20 Hs.'),
	(6, 'Conservatorio de Música de Tres Arroyos', 'Av. Rivadavia 417', 'conservatoriotresarroyos@abc.gob.ar', '02983-433883', 'https://ctresarroyos-bue.infd.edu.ar/sitio/', 'https://www.instagram.com/conservatoriodemusicatsas', 'https://www.facebook.com/conservatoriodemusicadetresarroyos/', NULL),
	(7, 'UCASAL - Universidad Católica de Salta', 'San Lorenzo 38', 'tresarroyos@ucasal.edu.ar', '02983-527463', 'https://www.ucasal.edu.ar/', 'https://www.instagram.com/aldeaeducativa/', 'https://www.facebook.com/UcasalTresArroyos/', NULL),
	(8, 'IFES Educación a Distancia', 'San Lorenzo 38', 'infodistancia@ifes.edu.ar', '02983-424229', 'http://ifes.edu.ar/distancia', 'https://www.instagram.com/aldeaeducativa/', 'https://www.facebook.com/aldeaeducativacentral', NULL),
	(9, 'ISIV Educación a Distancia', 'San Lorenzo 38', 'infodistancia@ifes.edu.ar', '02983-424229', 'http://ifes.edu.ar/distancia', 'https://www.instagram.com/ifesterciario', 'https://www.facebook.com/IFESdistancia', NULL),
	(10, 'ISSD Instituto Superior Santo Domingo', 'San Lorenzo 38', 'infodistancia@ifes.edu.ar', '02983-424229', 'http://ifes.edu.ar/distancia', 'https://www.instagram.com/aldeaeducativa/', 'https://www.facebook.com/aldeaeducativacentral', NULL),
	(11, 'Universidad de Belgrano', 'San Lorenzo 38', 'ug.tres.arroyos@fedev.ub.edu.ar', '02983-424229', 'https://www.ub.edu.ar/', NULL, NULL, 'Lunes a Viernes, de 8:30 a 12:30 y de 15:30 a 20:30'),
	(12, 'Universidad FASTA', 'San Lorenzo 38', 'uaa.tresarroyos@ufasta.edu.ar', '02983-424229 o al 02983-527463', 'https://www.ufasta.edu.ar/distancia/uaa-pba-ufasta-tres-arroyos/', 'https://www.ufasta.edu.ar/distancia/uaa-pba-ufasta-tres-arroyos/', 'https://www.facebook.com/ufastadistancia', 'Lunes a Viernes de 10:00 a 12:00 hs y de 16:00 a 19:00 hs.');
/*!40000 ALTER TABLE `institucion_educativa` ENABLE KEYS */;


-- Volcando estructura para tabla municipalidad.propuesta_academica
CREATE TABLE IF NOT EXISTS `propuesta_academica` (
  `id_propuesta` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(750) COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `periodo_inscripcion` varchar(450) COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `institucion` int(11) NOT NULL DEFAULT '0' COMMENT 'id de la institucion que lo dicta',
  `informacion` varchar(1950) COLLATE utf8_spanish_ci NOT NULL DEFAULT '0' COMMENT 'Puede poseer link a las instituciones donde aporte info del plan de estudio y demas',
  `visible` tinyint(1) unsigned zerofill DEFAULT '0' COMMENT 'Permite que pueda estar visible o no la carrera',
  PRIMARY KEY (`id_propuesta`)
) ENGINE=InnoDB AUTO_INCREMENT=223 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Se cargan todas las ofertas academicas privadas y publicas para darle informacion a los estudiantes futuros';

-- Volcando datos para la tabla municipalidad.propuesta_academica: ~211 rows (aproximadamente)
/*!40000 ALTER TABLE `propuesta_academica` DISABLE KEYS */;
INSERT INTO `propuesta_academica` (`id_propuesta`, `nombre`, `periodo_inscripcion`, `institucion`, `informacion`, `visible`) VALUES
	(1, 'Licenciatura en Administración', 'INSCRIPCION CERRADA', 1, 'http://www.cresta.edu.ar/academica/', 0),
	(2, 'Contador Público', 'INSCRIPCION CERRADA', 1, 'http://www.cresta.edu.ar/academica/', 0),
	(3, 'Tecnicatura Superior en Enfermería', 'INSCRIPCION CERRADA', 1, 'http://www.cresta.edu.ar/academica/', 0),
	(4, 'Tecnicatura Universitaria en Mantenimiento Industrial', 'INSCRIPCION CERRADA', 1, 'http://www.cresta.edu.ar/academica/', 0),
	(5, 'Tecnicatura Universitaria en Producción Agropecuaria Sostenible', '2 de Octubre 2023 al 23 de Febrero 2024', 1, 'http://www.cresta.edu.ar/academica/', 0),
	(6, 'Diplomatura Universitaria en Gestión del Comercio Exterior', '2 de Octubre 2023 al 23 de Febrero 2024', 1, 'http://www.cresta.edu.ar/academica/', 0),
	(7, 'Tecnicatura Universitaria en Gestión del Comercio Exterior y Régimen Aduanero', '2 de Octubre 2023 al 23 de Febrero 2024', 1, 'http://www.cresta.edu.ar/academica/', 0),
	(8, 'MATERIAS CBC - QUIMICA, IPC, ICSE', 'Febrero 2024', 1, 'http://www.cresta.edu.ar/academica/', 0),
	(9, 'Profesorado en Educación Inicial', '1 de Diciembre 2023 al 28 de Febrero 2024', 2, 'https://isfd167-bue.infd.edu.ar/sitio/oferta-de-carreras-2024/', 0),
	(10, 'Profesorado en Educación Primaria', '1 de Diciembre 2023 al 28 de Febrero 2024', 2, 'https://isfd167-bue.infd.edu.ar/sitio/oferta-de-carreras-2024/', 0),
	(11, 'Profesorado en Educación Secundaria en Geografía', '1 de Diciembre 2023 al 28 de Febrero 2024', 2, 'https://isfd167-bue.infd.edu.ar/sitio/oferta-de-carreras-2024/', 0),
	(12, 'Profesorado en Educación Secundaria en Historia', '1 de Diciembre 2023 al 28 de Febrero 2024', 2, 'https://isfd167-bue.infd.edu.ar/sitio/oferta-de-carreras-2024/', 0),
	(13, 'Tecnicatura Superior en Administración Contable', '1 de Diciembre 2023 al 28 de Febrero 2024', 2, 'https://isfd167-bue.infd.edu.ar/sitio/oferta-de-carreras-2024/', 0),
	(14, 'Tecnicatura Superior en Acompañamiento Terapéutico', '1 de Diciembre 2023 al 28 de Febrero 2024', 2, 'https://isfd167-bue.infd.edu.ar/sitio/oferta-de-carreras-2024/', 0),
	(15, 'Tecnicatura Superior en Publicidad', '1 de Diciembre 2023 al 28 de Febrero 2024', 2, 'https://isfd167-bue.infd.edu.ar/sitio/oferta-de-carreras-2024/', 0),
	(16, 'Tecnicatura Superior en Turismo', '1 de Diciembre 2023 al 28 de Febrero 2024', 2, 'https://isfd167-bue.infd.edu.ar/sitio/oferta-de-carreras-2024/', 0),
	(17, 'Tecnicatura Superior en Interpretación y Traducción de Lengua de Señas Argentina-España', '1 de Diciembre 2023 al 28 de Febrero 2024', 2, 'https://isfd167-bue.infd.edu.ar/sitio/oferta-de-carreras-2024/', 0),
	(18, 'Profesorado de educación Secundaria en Lengua y Literatura', '1 de Diciembre 2023 al 28 de Febrero 2024', 3, 'https://isfdyt33-bue.infd.edu.ar/sitio/', 0),
	(19, 'Profesorado de educación Secundaria en Matemática', '1 de Diciembre 2023 al 28 de Febrero 2024', 3, 'https://isfdyt33-bue.infd.edu.ar/sitio/', 0),
	(20, 'Profesorado de Educación Física', '1 de Diciembre 2023 al 28 de Febrero 2024', 3, 'https://isfdyt33-bue.infd.edu.ar/sitio/', 0),
	(21, 'Profesorado de Inglés', '1 de Diciembre 2023 al 28 de Febrero 2024', 3, 'https://isfdyt33-bue.infd.edu.ar/sitio/', 0),
	(22, 'Tecnicatura Superior en Trabajo Social', '1 de Diciembre 2023 al 28 de Febrero 2024', 3, 'https://isfdyt33-bue.infd.edu.ar/sitio/', 0),
	(23, 'Tecnicatura Superior en Higiene y Seguridad en el Trabajo', '1 de Diciembre 2023 al 28 de Febrero 2024', 3, 'https://isfdyt33-bue.infd.edu.ar/sitio/', 0),
	(24, 'Tecnicatura Superior en Industrias Agroalimentarias', '1 de Diciembre 2023 al 28 de Febrero 2024', 3, 'https://isfdyt33-bue.infd.edu.ar/sitio/', 0),
	(25, 'Tecnicatura Superior en Servicios Gastronómicos', '1 de Diciembre 2023 al 28 de Febrero 2024', 3, 'https://isfdyt33-bue.infd.edu.ar/sitio/', 0),
	(26, 'Tecnicatura Superior en Agroecología', '1 de Diciembre 2023 al 28 de Febrero 2024', 3, 'https://isfdyt33-bue.infd.edu.ar/sitio/', 0),
	(27, 'Tecnicatura Superior en Tiempo Libre y Recreación', '1 de Diciembre 2023 al 28 de Febrero 2024', 3, 'https://isfdyt33-bue.infd.edu.ar/sitio/', 0),
	(28, 'Tecnicatura Superior en Construcción sustentable', '1 de Diciembre 2023 al 28 de Febrero 2024', 3, 'https://isfdyt33-bue.infd.edu.ar/sitio/', 0),
	(29, 'Certificación Superior en Salud y Seguridad Ocupacional en el Trabajo en los establecimientos de salud', '1 de Diciembre 2023 al 28 de Febrero 2024', 3, 'https://isfdyt33-bue.infd.edu.ar/sitio/', 0),
	(30, 'Martillero, Corredor Público y Corredor Inmobiliario', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/martillero-y-corredor-publico-e-inmobiliario.pdf', 0),
	(31, 'Procurador', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/procurador.pdf', 0),
	(32, 'Tecnicatura En Administración y Gestión Tributaria', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-administracion-y-gestion-tributaria.pdf', 0),
	(33, 'Tecnicatura En Dirección de Equipos de venta', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-direccion-de-equipos-de-venta.pdf', 0),
	(34, 'Tecnicatura En Dirección de Protocolo, Organización de Eventos y RRPP', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-direccion-de-protocolo-org-de-eventos-y-rrpp.pdf', 0),
	(35, 'Tecnicatura En Diseño y Desarrollo de Videojuegos', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/brochure/tecnicatura-en-diseno-y-desarrollo-de-videojuegos_-siglo-21.pdf', 0),
	(36, 'Tecnicatura En Gestión Administrativas de Servicios de Salud', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-universitaria-gestion-administrativa-de-servicios-de-salud.pdf', 0),
	(37, 'Tecnicatura En Gestión Contable e impositiva', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-gestion-contable-e-impositiva.pdf', 0),
	(38, 'Tecnicatura En Gestión de Empresas Familiares', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-gestion-de-empresas-familiares.pdf', 0),
	(39, 'Tecnicatura En Higiene y Seguridad Laboral', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-higiene-y-seguridad-laboral.pdf', 0),
	(40, 'Tecnicatura En investigación de la escena del crimen', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-investigacion-de-la-escena-del-crimen.pdf', 0),
	(41, 'Tecnicatura En Marketing y Publicidad Digital', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-marketing-y-publicidad-digital.pdf', 0),
	(42, 'Tecnicatura En Relaciones Laborales', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-relaciones-laborales.pdf', 0),
	(43, 'Tecnicatura En Responsabilidad y Gestión Social', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-responsabilidad-y-gestion-social.pdf', 0),
	(44, 'Tecnicatura Universitaria En Administración de la Propiedad Horizontal y Conjuntos Inmobiliarios', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/brochure/tecnicatura-universitaria-en-administracion-de-la-propiedad-horizontal-y-conjuntos-inmobiliarios-siglo-21.pdf', 0),
	(45, 'Tecnicatura Universitaria En Administración y Gestión de Políticas Públicas', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-administracion-publica.pdf', 0),
	(46, 'Tecnicatura Universitaria En Diseño y Animación Digital', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-diseno-y-animacion-digital.pdf', 0),
	(47, 'Tecnicatura Universitaria En Gestión de Moda', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-gestion-de-moda.pdf', 0),
	(48, 'Tecnicatura Universitaria En Gestión del Clima Laboral de la Organización', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-gestion-del-clima-laboral.pdf', 0),
	(49, 'Tecnicatura Universitaria En Gestión y Auditorías Ambientales', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-universitaria-en-gestion-y-auditorias-ambientales.pdf', 0),
	(50, 'Tecnicatura Universitaria En Hidrocarburos y Geociencias', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-universitaria-en-hidrocarburos-y-geociencia.pdf', 0),
	(51, 'Tecnicatura Universitaria En Recursos Turísticos', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-gestion-de-recursos-turisticos.pdf', 0),
	(52, 'Tecnicatura Universitaria En Redes Informáticas y Telecomunicaciones', 'hasta el 18 de marzo 2024', 5, 'https://drive.google.com/file/d/1xoSFFYptDTMAFUqCwy4gNsBhFUuPkioZ/view', 0),
	(53, 'Tecnicatura Universitaria Promoción Comunitaria en Niñez y Adolescencia', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-universitaria-promocion-comunitaria-en-ninez-y-adolescencia.pdf', 0),
	(54, 'Abogacía', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/art-43/brochure-abogacia.pdf', 0),
	(55, 'Actuario', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/carreras/nuevas-carreras/brochure-actuario.pdf', 0),
	(56, 'Contador Público', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/art-43/brochure-contador_publico.pdf', 0),
	(57, 'Escribanía', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/escribania.pdf', 0),
	(58, 'Licenciatura En Administración', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-administracion.pdf', 0),
	(59, 'Licenciatura En Administración Agraria', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-administracion-agraria.pdf', 0),
	(60, 'Licenciatura En Administración de Infraestructura Tecnológica', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/carreras/nuevas-carreras/brochure-admin-de-infraestructura-tecnologica.pdf', 0),
	(61, 'Licenciatura En Administración de Servicios de Salud CCC', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/brochure/licenciatura-en-administracion-en-servicios-de-salud-siglo-21-1.pdf', 0),
	(62, 'Licenciatura En Administración Pública', 'hasta el 18 de marzo 2024', 5, 'https://drive.google.com/file/d/1UoACK7dksmv6s5mxXgV477PRoNAQzoZx/view', 0),
	(63, 'Licenciatura En Administración Hotelera', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-administracion-hotelera.pdf', 0),
	(64, 'Licenciatura En Antropología Organizacional', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/carreras/nuevas-carreras/brochure-antropologia-organizacional.pdf', 0),
	(65, 'Licenciatura En Bioinformática', 'hasta el 18 de marzo 2024', 5, '', 0),
	(66, 'Licenciatura En Ciencia Política y Gobierno', 'hasta el 18 de marzo 2024', 5, 'https://drive.google.com/file/d/1Uy4_j0TpeMZdpCnWJZcU7XKOiS4-6UnI/view', 0),
	(67, 'Licenciatura En Ciencias de Datos', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/carreras/nuevas-carreras/brochure-ciencia_datos.pdf', 0),
	(68, 'Licenciatura En Comercialización (Marketing)', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-comercializacion.pdf', 0),
	(69, 'Licenciatura En Comercio Internacional', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-comercio-internacional.pdf', 0),
	(70, 'Licenciatura En Criminología y Seguridad', 'hasta el 18 de marzo 2024', 5, '', 0),
	(71, 'Licenciatura En Diseño y Animación Digital', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-diseno-y-animacion-digital.pdf', 0),
	(72, 'Licenciatura En Educación (CCC)', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-educacion.pdf', 0),
	(73, 'Licenciatura En Educación y Nuevas Tecnologías', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/carreras/nuevas-carreras/brochure-lic.en-educacion-y-nuevas-tecnologias.pdf', 0),
	(74, 'Licenciatura En Emprendimiento - CCC', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/carreras/nuevas-carreras/brochure-emprendimiento.pdf', 0),
	(75, 'Licenciatura En Finanzas', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/brochure/licenciatura-en-finanzas-corporativas-y-mercado-de-valores-siglo-21.pdf', 0),
	(76, 'Licenciatura En Gerontología', 'hasta el 18 de marzo 2024', 5, '', 0),
	(77, 'Licenciatura En Gestión Ambiental', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-gestion-ambiental.pdf', 0),
	(78, 'Licenciatura En Gestión de Recursos Humanos', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-gestion-rrhh.pdf', 0),
	(79, 'Licenciatura En Gestión Turística', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-gestion-turistica.pdf', 0),
	(80, 'Licenciatura En Higiene, Seguridad y Medio ambiente del Trabajo', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/pregrado/tec-higiene-y-seguridad-laboral.pdf', 0),
	(81, 'Licenciatura En Informática', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/art-43/brochure-informatica.pdf', 0),
	(82, 'Licenciatura En Inteligencia Artificial y Robótica', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/carreras/nuevas-carreras/brochure-inteligencia-artificial-y-robotica-.pdf', 0),
	(83, 'Licenciatura En Logística Global', 'hasta el 18 de marzo 2024', 5, 'https://drive.google.com/file/d/1Mmahc8Dqjeg3PCKNJowmCKFo-Y2gRpeM/view', 0),
	(84, 'Licenciatura En Matemática', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/carreras/nuevas-carreras/brochure-matematica.pdf', 0),
	(85, 'Licenciatura En Periodismo', 'hasta el 18 de marzo 2024', 5, 'https://drive.google.com/file/d/1fU4-XdFo8f4cMjkYR3v3FQr8HRTBol_g/view', 0),
	(86, 'Licenciatura En Publicidad', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-publicidad.pdf', 0),
	(87, 'Licenciatura En Relaciones Internacionales', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-relaciones-internacionales.pdf', 0),
	(88, 'Licenciatura En Relaciones Públicas e Institucionales', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/pdf/carreras/grado/lic-relaciones-publicas.pdf', 0),
	(89, 'Licenciatura En Seguridad Informática', 'hasta el 18 de marzo 2024', 5, 'https://contenidos.21.edu.ar/descargas/carreras/nuevas-carreras/brochure-seguridad-informatica.pdf', 0),
	(90, 'Licenciatura En Terapia Ocupacional y Desarrollo Humano', 'hasta el 18 de marzo 2024', 5, '', 0),
	(91, 'Profesorado de Música Orientación en Educación Musical', '5 de Diciembre 2023 al 8 de Marzo 2024', 6, '', 0),
	(92, 'Profesorado en Música Orientación Instrumento: Piano, Guitarra, Percusión, Flauta, Violín, Clarinete y Saxo', '5 de Diciembre 2023 al 8 de Marzo 2024', 6, '', 0),
	(93, 'Tecnicatura en Capacitación Instrumental: Piano, Guitarra, Percusión, Flauta, Violín, Clarinete y Saxo', '5 de Diciembre 2023 al 8 de Marzo 2024', 6, '', 0),
	(94, 'Formación Básica en Música: Piano, Guitarra, Percusión, Flauta, Violín, Clarinete y Saxo (A partir de los 9 años)', '5 de Diciembre 2023 al 8 de Marzo 2024', 6, '', 0),
	(95, 'Formación Básica en Música Popular: guitarra eléctrica y bajo eléctrico (A partir de los 14 años)', '5 de Diciembre 2023 al 8 de Marzo 2024', 6, '', 0),
	(96, 'Tec. Sup. en Análisis de Sistemas de Computación', 'hasta el 5 de abril 2024', 10, 'https://www.aldeaeducativa.ag/educacion/tec_analisis_sistemas_computacion', 0),
	(97, 'Tec. Sup en Sistemas de Telecomunicaciones', 'hasta el 5 de abril 2024', 10, 'https://www.aldeaeducativa.ag/educacion/tec_sistemas_de_telecomunicaciones', 0),
	(98, 'Tec.a Sup. en Desarrollo de Software', 'hasta el 5 de abril 2024', 10, 'https://www.aldeaeducativa.ag/educacion/tecnicatura_superior_en_desarrollo_de_software_1%C2%B0_semestre_', 0),
	(99, 'Téc. Sup. en Ciencia de Datos E Inteligencia Artificial', 'hasta el 5 de abril 2024', 10, 'https://www.aldeaeducativa.ag/educacion/tecnico_superior_en_ciencia_de_datos_e_inteligencia_artificial___issd', 0),
	(100, 'Seguridad e Higiene Laboral', 'hasta el 29 de febrero 2024', 9, '', 0),
	(101, 'Negocios Digitales', 'hasta el 29 de febrero 2024', 9, 'https://www.aldeaeducativa.ag/educacion/tecnico_superior_en_negocios_digitales', 0),
	(102, 'Analista de Sistemas', 'hasta el 29 de febrero 2024', 9, 'https://www.aldeaeducativa.ag/educacion/tecnicatura_superior_en_analisis_de_sistemas', 0),
	(103, 'Administración de Empresas', 'hasta el 29 de febrero 2024', 9, 'https://www.aldeaeducativa.ag/educacion/tecnico_superior_en_administracion_de_empresas_', 0),
	(104, 'Recursos Humanos', 'hasta el 29 de febrero 2024', 9, 'https://www.aldeaeducativa.ag/educacion/curso_de_recursos_humanos_', 0),
	(105, 'Marketing Digital', 'hasta el 29 de febrero 2024', 9, 'https://www.aldeaeducativa.ag/educacion/tecnico_superior_en_marketing_digital', 0),
	(106, 'Turismo', 'hasta el 29 de febrero 2024', 9, 'https://www.aldeaeducativa.ag/educacion/tecnico_superior_en_turismo', 0),
	(107, 'Bachillerato para Jóvenes y Adultos a Distancia', 'hasta el 29 de febrero 2024', 9, 'https://www.aldeaeducativa.ag/educacion/bachillerato_a_distancia_para_adultos', 0),
	(108, 'Tec. Univ. en Hotelería y Turismo', 'hasta el 31 de marzo 2024', 11, 'https://www.ub.edu.ar/facultad-de-estudios-distancia-y-educacion-virtual/distancia-tecnicatura-en-hoteleria-y-turismo', 0),
	(109, 'Tec. Univ. en Producción Agraria', 'hasta el 31 de marzo 2024', 11, 'https://www.ub.edu.ar/facultad-de-estudios-distancia-y-educacion-virtual/fedev-tecnicatura-en-produccion-agraria', 0),
	(110, 'Tec. Universitaria en Logística de Agronegocios', 'hasta el 31 de marzo 2024', 11, 'https://www.ub.edu.ar/modalidad-virtual/virtual-tecnicatura-universitaria-en-logistica-de-agronegocios', 0),
	(111, 'Tec. Universataria en Logística', 'hasta el 31 de marzo 2024', 11, 'https://www.ub.edu.ar/facultad-de-estudios-distancia-y-educacion-virtual/fedev-tecnicatura-universitaria-en-logistica', 0),
	(112, 'Tec. en Administración y Orientación de PYME', 'hasta el 31 de marzo 2024', 11, 'https://www.ub.edu.ar/facultad-de-estudios-distancia-y-educacion-virtual/fedev-tecnicatura-en-administracion-orientacion', 0),
	(113, 'Tec. en Comercio Internacional', 'hasta el 31 de marzo 2024', 11, 'https://www.ub.edu.ar/facultad-de-estudios-distancia-y-educacion-virtual/fedev-tecnicatura-en-comercio-internacional', 0),
	(114, 'Tec. en Comercialización', 'hasta el 31 de marzo 2024', 11, 'https://www.ub.edu.ar/facultad-de-estudios-distancia-y-educacion-virtual/fedev-tecnicatura-en-comercializacion', 0),
	(115, 'Tec. Analista Univ. en Gestión de - Capital Humano', 'hasta el 31 de marzo 2024', 11, 'https://www.ub.edu.ar/modalidad-virtual/fedev-analista-universitario-en-gestion-de-capital-humano', 0),
	(116, 'Lic. Hotelería y Turismo - Ciclo Complementario', 'hasta el 31 de marzo 2024', 11, 'https://www.ub.edu.ar/modalidad-virtual/distancia-licenciatura-en-hoteleria-y-turismo', 0),
	(117, 'Lic. Gestión de Agroempresas - Ciclo Complementario', 'hasta el 31 de marzo 2024', 11, 'https://www.ub.edu.ar/modalidad-virtual/fedev-licenciatura-en-gestion-de-agroempresas', 0),
	(118, 'Lic. Logistica Integral - Ciclo Complementario', 'hasta el 31 de marzo 2024', 11, 'https://www.ub.edu.ar/facultad-de-estudios-distancia-y-educacion-virtual/fedev-licenciatura-en-logistica-integral', 0),
	(119, 'Lic. Gestión de Cap. Humano - Ciclo Complementario', 'hasta el 31 de marzo 2024', 11, 'https://www.ub.edu.ar/facultad-de-estudios-distancia-y-educacion-virtual/fedev-licenciatura-en-gestion-de-capital-humano', 0),
	(121, 'Contador Público', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/contador-publico-a-distancia/', 0),
	(122, 'Derecho', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/abogacia-a-distancia/', 0),
	(123, 'Escribanía', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/escribania-a-distancia/', 0),
	(124, 'Corredor Inmobiliario y Martillero Publico', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/corredor-inmobiliario-y-martillero-publico-a-distancia/', 0),
	(125, 'Procuración', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/procuracion-a-distancia/', 0),
	(126, 'Lic. en Economía', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-economia-a-distancia/', 0),
	(127, 'Lic. en Adm. de Empresas', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-administracion-de-empresas-a-distancia/', 0),
	(128, 'Lic. En Adm. de Negocios Digitales', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-administracion-de-negocios-digitales/', 0),
	(129, 'Lic. En Ciencias de Datos', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-ciencia-de-datos/', 0),
	(130, 'Lic. en Relaciones Internacionales', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-relaciones-internacionales-a-distancia/', 0),
	(131, 'Lic. En Relaciones Publicas', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-relaciones-publicas-e-institucionales-a-distancia/', 0),
	(132, 'Lic. en Comercialización', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-comercializacion-a-distancia/', 0),
	(133, 'Lic. En Eficiencia Energética', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-eficiencia-energetica/', 0),
	(134, 'Lic. En Adm. Agropecuria', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-administracion-agropecuaria-a-distancia/', 0),
	(135, 'Lic. Recursos Humanos', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-recursos-humanos-a-distancia-2/', 0),
	(136, 'Lic. Higiene y Seguridad', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-higiene-y-seguridad-en-el-trabajo-2/', 0),
	(137, 'Lic. en Seguridad - Ciclo Complementario', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-seguridad-ciclo-de-complementacion-curricular-a-distancia/', 0),
	(138, 'Lic. en Educación Física - Ciclo Complementario', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-educacion-fisica-ciclo-de-complementacion-curricular-a-distancia/', 0),
	(139, 'Lic. En Adm. y Gestión Univ. - Ciclo Complementario', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-administracion-y-gestion-universitaria-ccc/', 0),
	(140, 'Lic. En Criminología - Ciclo Complementario', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/licenciatura-en-administracion-de-negocios-digitales/', 0),
	(141, 'Lic. En Entr. Deportivo - Ciclo Complementario', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/licenciatura-en-entrenamiento-deportivo-ciclo-de-complementacion-curricular-a-distancia/', 0),
	(142, 'Lic. En Lenguaje Expresivo - Ciclo Complementario', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/elementor-59082/', 0),
	(143, 'Lic. en Gestión Educativa - Ciclo Complementario', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/licenciatura-en-gestion-educativa-ciclo-de-complementacion-curricular-a-distancia/', 0),
	(144, 'Lic. Comercio Exterior', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/carrera-de-licenciatura-en-comercio-internacional-a-distancia/', 0),
	(145, 'Tec. en Higiene y Seguridad', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/tecnicatura-en-higiene-y-seguridad-en-el-trabajo/', 0),
	(146, 'Tec. Gestión de Bancos', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/tecnicatura-en-gestion-de-bancos-empresas-financieras-y-de-seguros/', 0),
	(147, 'Tec. En Gestion de Calidad', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/tecnicatura-universitaria-en-gestion-de-calidad-a-distancia/', 0),
	(148, 'Tec. Univ. En Seguridad Informática', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/tecnicatura-universitaria-en-seguridad-informatica-a-distancia/', 0),
	(149, 'Tec. Operaciones Mineras e Industriales', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/tecnicatura-en-operaciones-mineras-e-industriales/', 0),
	(150, 'Tec. Univ. Organizacion y Direccion de Eventos', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/tecnicatura-universitaria-en-organizacion-y-direccion-de-eventos-y-ceremonial/', 0),
	(151, 'Tec. Gestión de Bancos, Empresa Financieras y Seguros', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/tecnicatura-en-gestion-de-bancos-empresas-financieras-y-de-seguros/', 0),
	(152, 'Secretariado Ejecutivo', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/tecnicatura-universitaria-en-secretariado-ejecutivo-a-distancia/', 0),
	(153, 'Ceremonial y Protocolo', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/carrera/por-modalidad/carreras-a-distancia/tecnicatura-universitaria-en-organizacion-y-direccion-de-eventos-y-ceremonial/', 0),
	(154, 'Maestria Administracion de Negocios', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/maestria-en-administracion-de-negocios-distancia/', 0),
	(155, 'Maestria en Gestion Ambiental', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/maestria-en-gestion-ambiental-distancia-2/', 0),
	(156, 'Maestria Gestion de Obras y Desarrollos Inmob.', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/maestria-en-gestion-de-proyectos-obras-y-desarrollos-inmobiliarios/', 0),
	(157, 'Maestria en Derecho del Trabajo', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/maestria-en-derecho-del-trabajo-distancia/', 0),
	(158, 'Maestría en Gestión de Turismo Sostenible', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/maestria-en-gestion-del-turismo-sostenible/', 0),
	(159, 'Maestría en Ciencias de Datos', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/maestria-en-ciencias-de-datos-distancia/', 0),
	(160, 'Maestría en Prevención y Control de Infecciones', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/maestria-en-prevencion-y-control-de-infecciones/', 0),
	(161, 'Maestría en Nutrición y Entrenamiento Deportivo', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/maestria-en-entrenamiento-y-nutricion-deportiva-distancia/', 0),
	(162, 'Esp. En Dirección de RRHH', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/especializacion-en-direccion-de-recursos-humanos-distancia/', 0),
	(163, 'Esp. En Inteligencia de Negocios', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/general/especializacion-en-inteligencia-de-negocios/', 0),
	(164, 'Esp. En Industria y Transformación digital', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/general/especializacion-en-industria-y-trasformacion-digital/', 0),
	(165, 'Esp. En Big Data', 'hasta el 1 de marzo 2024', 7, '	https://www.ucasal.edu.ar/general/especializacion-en-big-data-y-analisis-en-datos-estrategicos/', 0),
	(166, 'Esp. Evaluacion Impacto Ambiental', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/especializacion-en-evaluacion-de-impacto-ambiental-distancia/', 0),
	(167, 'Esp. En Derecho de Familia', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/especializacion-en-derecho-de-familia-distancia/', 0),
	(168, 'Esp. en Act. Fisica Deporte y Salud', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/especializacion-en-deportes-y-actividad-fisica-para-la-salud-distancia/', 0),
	(169, 'Esp. en Higiene y Seguridad en el Trabajo', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/especializacion-en-seguridad-e-higiene-en-el-trabajo-distancia/', 0),
	(170, 'Esp. En Finanzas de Empresas', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/especializacion-en-finanzas-de-empresas-distancia/', 0),
	(171, 'Esp. Orientación en Neurodesarrollo y aprendizaje', 'hasta el 1 de marzo 2024', 7, 'https://www.ucasal.edu.ar/especializacion-en-seguridad-e-higiene-en-el-trabajo-distancia/', 0),
	(172, 'Tec. en Administración de Empresas', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/tecnicatura-superior-en-administracion-de-empresas/', 0),
	(173, 'Tec. en Gestión Ambiental', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/tecnicatura-superior-en-gestion-ambiental/', 0),
	(174, 'Tec. en Higiene y Seguridad', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/tecnicatura-superior-en-higiene-y-seguridad/', 0),
	(175, 'Tec. en Recursos Humanos', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/tecnicatura-en-recursos-humanos/', 0),
	(176, 'Tec. Geología', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/tecnicatura-superior-en-geologia/', 0),
	(177, 'Tec. en Desarrollo de Software', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/tecnicatura-superior-en-desarrollo-de-software/', 0),
	(178, 'Tec. en Energías Renovables', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/tecnicatura-superior-en-energias-renovables/', 0),
	(179, 'Tec. en Hidrocarburos', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/tecnicatura-superior-en-hidrocarburos/', 0),
	(180, 'Tec. en Topografía', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/tecnicatura-superior-en-topografia/', 0),
	(181, 'Psicología en las Empresas y Organizaciones', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/diplomatura-en-psicologia-en-las-empresas-y-organizaciones/', 0),
	(182, 'Dipl. Auxiliar en Hidrocarburos', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/diplomatura-en-auxiliar-en-hidrocarburos/', 0),
	(183, 'Marketing con Orientación a Entornos Virtuales', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/tecnicatura-superior-en-marketing/', 0),
	(184, 'Diplomatura en Actividad Física y Salud', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/diplomatura-en-actividad-fisica-y-salud/', 0),
	(185, 'Administración de Sueldos e Impuestos', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/diplomatura-en-administracion-de-sueldos-e-impuestos/', 0),
	(186, 'Líder de Ventas', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/diplomatura-en-lider-de-ventas/', 0),
	(187, 'Sop. de Infraestructura de Tec. de la Información', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/tecnicatura-superior-en-soporte-de-infraestructura-de-tecnologia-de-la-informacion/', 0),
	(188, 'Ciencia de Datos e Inteligencia Artificial', 'Abiertas', 8, 'https://ifes.edu.ar/distancia/tecnicatura-superior-en-ciencia-de-datos-e-inteligencia-artificial/', 0),
	(189, 'Derecho', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/abogacia-distancia/', 0),
	(190, 'Contador Público', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/carreras/contador-publico-distancia-2/', 0),
	(191, 'Martillero y Corredor Público', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/martillero-y-corredor-publico-dist/', 0),
	(192, 'Lic. en Higiene y Seguridad', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-hig-y-seg-en-el-trabajo/', 0),
	(193, 'Lic. en Ciberseguridad', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/lic-ciberseguridad/', 0),
	(194, 'Lic. en Ingles - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-ingles/', 0),
	(195, 'Lic. en Educación - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-educacion/', 0),
	(196, 'Lic. en Adm. de Empresas - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-administracion/', 0),
	(197, 'Lic. en Markenting - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-marketing/', 0),
	(198, 'Lic. en Periodismo - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-periodismo/', 0),
	(199, 'Lic. en Tecnología Educativa - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/lic-en-tecnologia-educativa/', 0),
	(200, 'Lic. en Educación Física - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-educacion-fisica/', 0),
	(201, 'Lic. en Psicopedagogía - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-psicopedagogia/', 0),
	(202, 'Lic. en Seguridad Ciudadana - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-seguridad-ciudadana/', 0),
	(203, 'Lic. en Corretaje Inmobiliario - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-corretaje-inmobiliario-ciclo-de-complementacion-curricular/', 0),
	(204, 'Lic. Archivología', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-archivologia/', 0),
	(205, 'Lic. en Turismo - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-turismo/', 0),
	(206, 'Lic. Negocios Digitales - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-desarrollo-de-negocios-digitales/', 0),
	(207, 'Lic. en Educación Religiosa - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/humanidades/carreras/licenciatura-en-educacion-religiosa/', 0),
	(208, 'Lic. en Pedagogía de la Educación Religiosa', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/humanidades/licenciatura-en-pedagogia-de-la-educacion-religiosa/', 0),
	(209, 'Lic. Gest. del Talento Humano - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-gestion-del-talento-humano-ciclo-complementario/', 0),
	(210, 'Lic. en Comunicación Social', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-comunicacion-social/', 0),
	(211, 'Lic. Diseño y Com. Transmedia - Ciclo Complementario', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-diseno-y-comunicacion-transmedia-ciclo-complementario/', 0),
	(212, 'Lic. en RR. HH Inscripciones', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-recursos-humanos/', 0),
	(213, 'Lic. Publicidad y Narrativas Digitales', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-publicidad-y-narrativas-digitales/', 0),
	(214, 'Lic. Gestión de la Comunicación Estratégica', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/licenciatura-en-gestion-de-la-comunicacion-estrategica/', 0),
	(215, 'Tec. en Acompañamiento Terapeutico', 'PROXIMAMENTE', 12, 'https://www.tecnicaturaat.ar/web/tecnicaturaat/', 0),
	(216, 'Tec. Universitaria en Adm. de PYME', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/tecnicatura-en-adm-de-pymes/', 0),
	(217, 'Tec. en Seguridad Ciudadana', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/tecnicatura-en-seguridad-ciudadana/', 0),
	(218, 'Tec. en Higiene y Seguridad', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/tecnicatura-en-higiene-y-seguridad-en-el-trabajo-2/', 0),
	(219, 'Tec. en Hostelería', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/tecnicatura-universitaria-en-hoteleria/', 0),
	(220, 'Tec. en Turismo', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/tecnicatura-universitaria-en-turismo/', 0),
	(221, 'Esp. Informática Forense', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/especializacion-en-informatica-forense/', 0),
	(222, 'Esp. en Proyectos Educativos', 'hasta el 15 de abril 2024', 12, 'https://www.ufasta.edu.ar/distancia/especializacion-educacion/', 0);
/*!40000 ALTER TABLE `propuesta_academica` ENABLE KEYS */;
